---
- name: Upgrade CUDA from 12.2 to 12.4
  hosts: "*"
  become: yes
  tasks:
    - name: Ensure dpkg is not interrupted
      command: sudo dpkg --configure -a
      ignore_errors: yes

    - name: Remove existing CUDA and related packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      with_items:
        - "*cublas*"
        - "cuda*"
        - "nsight*"
        - "libcudnn*"
      ignore_errors: yes

    - name: Autoremove unused packages
      apt:
        autoremove: yes
      ignore_errors: yes

    - name: Autoclean package cache
      apt:
        autoclean: yes
      ignore_errors: yes

    - name: Remove CUDA directories
      shell: rm -rf /usr/local/cuda*
      ignore_errors: yes

    - name: Remove conflicting NVIDIA packages
      shell: dpkg --force-all --purge {{ item }}
      with_items:
        - nvidia-kernel-common-535
        - nvidia-compute-utils-535
        - nvidia-firmware-535-535.183.01
      ignore_errors: yes

    - name: Remove old keyrings and repository entries
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/cuda.list
        - /usr/share/keyrings/cuda-archive-keyring.gpg
      ignore_errors: yes

    - name: Add the CUDA keyring
      apt_key:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        state: present
      ignore_errors: yes

    - name: Manually add the CUDA GPG key if automatic method fails
      shell: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        sudo apt-key add 3bf863cc.pub
      when: apt_key.msg is defined and '"404" in apt_key.msg'

    - name: Create CUDA repository file
      copy:
        dest: /etc/apt/sources.list.d/cuda.list
        content: |
          deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /

    - name: Update package lists
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Fix broken dependencies
      command: sudo apt --fix-broken install -y
      ignore_errors: yes

    - name: Install NVIDIA driver
      apt:
        name: nvidia-driver-535
        state: present
      ignore_errors: yes

    - name: Install CUDA 12.4
      apt:
        name: cuda-12-4
        state: present
      ignore_errors: yes

    - name: Set environment variables
      lineinfile:
        dest: ~/.bashrc
        line: "{{ item }}"
        state: present
      with_items:
        - 'export PATH=/usr/local/cuda-12.4/bin${PATH:+:${PATH}}'
        - 'export LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}'

    - name: Source bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

    - name: Verify CUDA installation
      shell: /usr/local/cuda-12.4/bin/nvcc --version
      register: cuda_version

    - name: Print CUDA version
      debug:
        var: cuda_version.stdout
