---
- name: Disable Unattended Upgrades and Related Services
  hosts: "*"
  become: yes  # Ensures that the tasks are run with sudo
  tasks:
    - name: Purge unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: absent
        purge: yes
        autoremove: yes

    - name: Disable apt-daily-upgrade.timer
      systemd:
        name: apt-daily-upgrade.timer
        enabled: no
        state: stopped

    - name: Mask apt-daily-upgrade.service
      systemd:
        name: apt-daily-upgrade.service
        masked: yes
        state: stopped

    - name: Disable apt-daily.timer
      systemd:
        name: apt-daily.timer
        enabled: no
        state: stopped

    - name: Mask apt-daily.service
      systemd:
        name: apt-daily.service
        masked: yes
        state: stopped
