---
- name: Run commands as sudo
  hosts: "*"
  become: yes

  tasks:
    - name: Remove docker-compose
      apt:
        name: docker-compose
        state: absent

    - name: Download docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symlink for docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Update apt and install gettext-base
      apt:
        update_cache: yes
        name: gettext-base
        state: present

    - name: Download docker-compose.yml
      get_url:
        url: https://raw.githubusercontent.com/jjziets/DCMontoring/main/client/docker-compose.yml-vast
        dest: /home/{{ ansible_user }}/docker-compose.yml

    - name: Download check-upgradable-packages.sh
      get_url:
        url: https://github.com/jjziets/gddr6_temps/raw/master/update-package-count.sh
        dest: /usr/local/bin/check-upgradable-packages.sh
        mode: '0755'

    - name: Add cron job for check-upgradable-packages.sh
      cron:
        name: "Check upgradable packages"
        minute: "0"
        hour: "*"
        job: "/usr/local/bin/check-upgradable-packages.sh"

    - name: Pull docker-compose images
      command: docker-compose pull
      args:
        chdir: /home/{{ ansible_user }}

    - name: Update and run docker-compose
      shell: |
        sed "s/__HOST_HOSTNAME__/$(hostname)/g" docker-compose.yml | docker-compose -f - up -d
      args:
        chdir: /home/{{ ansible_user }}

    - name: Download install_node_exporter.sh
      get_url:
        url: https://raw.githubusercontent.com/jjziets/DCMontoring/main/client/install_node_exporter.sh
        dest: /home/{{ ansible_user }}/install_node_exporter.sh
        mode: '0755'

    - name: Run install_node_exporter.sh
      command: ./install_node_exporter.sh
      args:
        chdir: /home/{{ ansible_user }}

    - name: Download install_NvidiaDCGM_Exporter.sh
      get_url:
        url: https://raw.githubusercontent.com/jjziets/DCMontoring/main/client/install_NvidiaDCGM_Exporter.sh
        dest: /home/{{ ansible_user }}/install_NvidiaDCGM_Exporter.sh
        mode: '0755'

    - name: Run install_NvidiaDCGM_Exporter.sh
      command: ./install_NvidiaDCGM_Exporter.sh
      args:
        chdir: /home/{{ ansible_user }}

    - name: Download and setup gddr6-metrics-exporter
      shell: |
        wget -q -O /usr/local/bin/gddr6-metrics-exporter_supervisor_script.sh https://raw.githubusercontent.com/jjziets/gddr6_temps/master/gddr6-metrics-exporter_supervisor_script.sh && \
        chmod +x /usr/local/bin/gddr6-metrics-exporter_supervisor_script.sh && \
        wget -q -O /etc/systemd/system/gddr6-metrics-exporter.service https://raw.githubusercontent.com/jjziets/gddr6_temps/master/gddr6-metrics-exporter.service && \
        systemctl daemon-reload && \
        systemctl enable gddr6-metrics-exporter && \
        systemctl start gddr6-metrics-exporter

    - name: Download docker-compose (RunPod version)
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symlink for docker-compose (RunPod version)
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Update apt and install gettext-base (RunPod version)
      apt:
        update_cache: yes
        name: gettext-base
        state: present

    - name: Download docker-compose.yml (RunPod version)
      get_url:
        url: https://raw.githubusercontent.com/jjziets/DCMontoring/main/client/docker-compose.yml-runpod
        dest: /home/{{ ansible_user }}/docker-compose.yml

    - name: Run docker-compose (RunPod version)
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}
